<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVEO5snY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVEO5snY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVEO5snY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVEO5snY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVEO5snY\App_KernelDevDebugContainer([
    'container.build_hash' => 'VEO5snY',
    'container.build_id' => 'e7de6bdc',
    'container.build_time' => 1612107208,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVEO5snY');
